# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160706_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(upload_to=''),
        ),
    ]
