# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_rating',
            field=models.CharField(choices=[('L', 'Lame'), ('G', 'Good'), ('A', 'Awesome')], default=datetime.datetime(2016, 7, 7, 10, 42, 54, 905008, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
